### ISSUE TITLE
small bug in constructor

### ISSUE THREAD

**Issue by llerrito** [yurablok/sorted_flat_deque#1]
m_comparator assigment is missing  

sorted_flat_deque<item_t>& operator=(const sorted_flat_deque<item_t>& other) {
        m_size = other.m_size;
        m_minOffset = other.m_minOffset;
        m_medianOffset = other.m_medianOffset;
        m_medianPos = other.m_medianPos;
        m_maxOffset = other.m_maxOffset;
        m_nodes = other.m_nodes;
        return *this;
    }
    sorted_flat_deque<item_t>& operator=(sorted_flat_deque<item_t>&& other) {
        m_size = other.m_size; other.m_size = 0;
        m_minOffset = other.m_minOffset; other.m_minOffset = position_max;
        m_medianOffset = other.m_medianOffset; m_medianOffset = position_max;
        m_medianPos = other.m_medianPos; m_medianPos = position_max;
        m_maxOffset = other.m_maxOffset; m_maxOffset = position_max;
        m_nodes = std::move(other.m_nodes);
        return *this;
    }

**Comment by yurablok** [comment]
Thank you! Fixed in v0.3.
